#ifndef __BIBLIOTECA_PRUEBAS_HASH__
#define __BIBLIOTECA_PRUEBAS_HASH__

#define ERROR -1
#define EXITO 0;

int DadaUnaCapacidadMinimaCero_SeIntentaCrearUnHash_DevuelveNULL();
int DadoUnHashNULL_SeIntentaInsertarUnElemento_DevuelveERROR();
int DadoUnHashNULL_SeIntentaQuitarUnElemento_DevuelveERROR();
int DadoUnHashNULL_SeQuiereObtenerUnElemento_DevuelveNULL();
int DadoUnHashNULL_SePreguntaSiContieneUnElemento_DevuelveFalse();
int DadoUnHashNULL_SePreguntaLaCantidadDeElementos_DevuelveCero();
int DadoUnHashVacio_SeQuiereQuitarUnElemento_DevuelveERROR();
int DadoUnHashVacio_SeQuiereObtenerUnElemento_DevuelveNULL();
int DadoUnHashVacio_SePreguntaSiContieneUnElemento_DevuelveFalse();
int DadoUnHashVacio_SePreguntaLaCantidadDeElementos_DevuelveCero();
int DadoUnHashVacio_SeIntentaInsertarUnElementoConUnaClaveNULL_DevuelveERROR();
int DadoUnHashConMuchosElementos_SeIntentaQuitarUnElementoConClaveNULL_DevuelveERROR();
int DadoUnHashConMuchosElementos_SeIntentaObtenerUnElementoConClaveNULL_DevuelveNULL();
int DadoUnHashConMuchosElementos_SePreguntaSiContieneUnElementoConClaveNULL_DevuelveFalse();
int DadoUnHashConMuchosElementos_SeIntentaQuitarUnElementoConUnaClaveQueNoEsta_DevuelveERROR();
int DadoUnHashConMuchosElementos_SeIntentaObtenerUnElementoConUnaCLaveQueNoEsta_DevuelveNULL();
int DadoUnHashConMuchosElementos_SePreguntaSiContieneUnElementoConUnaClaveQueNoEsta_DevuelveFalse();
int DadoUnHashVacio_SeInsertanDiezElementosYPreguntoLaCantidadDeElementosEnElHash_DevuelveDiez();
int DadoUnHashConDiezElementos_SeQuitanLosDiezElementosYSePreguntaLaCantidad_DevuelveCero();
int DadoUnHashNULL_SeLoDestruyeNoCausaProblemas();
int DadoUnHashNull_SeIntentaCrearUnIteradorParaDichoHash_DevuelveNULL();
int DadoUnHashVacio_SeIntentaCrearUnIteradorParaDichoHash_DevuelveNULL();
int DadoUnIteradorNULL_SePreguntaSiTieneSiguiente_Devuelvefalse();
int DadoUnIteradorNULL_SeIntentaAvanzarAlSiguienteElemento_DevuelveNULL();
int DadoUnIteradorNULL_SeLoDestruye_NoCausaProblemas();
int DadoUnHashConCapacidadMinimaDos_SeInsertanDiezElementos_LaTablaDeHashSeRedimensionaCorrectamente();

#endif /*__BIBLIOTECA_PRUEBAS_HASH__*/
